### ISSUE TITLE
Error when using a more complex filter condition. 

### ISSUE THREAD

**Issue by dtboctor** [scanamo/scanamo#155]
This could be my issue, but it seems to compile fairly well.  I am using this code to do a server side filter

```
Scanamo.exec(client)(
        table
          .filter(
            attributeExists('numTries)
              and attributeExists('numCorrect)
              and attributeExists('score)
              and attributeExists('responseTime)
              and ('gameId -> gameId)
              and SymbolKeyCondition('responseTime) > 0
              and SymbolKeyCondition('numTries) > 5

          )
          .limit(limit)
          .query('userId -> userId descending)
```

However, I'm ending up with an error: 

```
17/10/17 01:11:34 WARN TaskSetManager: Lost task 6.1 in stage 7.0 (TID 30, ip-172-16-0-110.ec2.internal, executor 1): com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: Value provided in ExpressionAttributeNames unused in expressions: keys: {#and_l_and_l_and_l_and_l_and_r_conditionttr, #and_l_and_r_condition, #and_l_and_l_and_l_and_r_conditionttr} (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: NOBURJ6UAIQDKLGBEO456KODKBVV4KQNSO5AEMVJF66Q9ASUAAJG)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1592)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1257)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1029)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:741)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:665)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:647)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:511)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:2186)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:2162)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeQuery(AmazonDynamoDBClient.java:1589)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.query(AmazonDynamoDBClient.java:1565)
	at com.gu.scanamo.ops.ScanamoInterpreters$$anon$1.apply(ScanamoInterpreters.scala:49)
	at com.gu.scanamo.ops.ScanamoInterpreters$$anon$1.apply(ScanamoInterpreters.scala:30)
	at cats.free.Free$$anonfun$foldMap$1.apply(Free.scala:126)
	at cats.free.Free$$anonfun$foldMap$1.apply(Free.scala:124)
	at cats.package$$anon$1.tailRecM(package.scala:41)
	at cats.free.Free.foldMap(Free.scala:124)
	at cats.free.Free$$anonfun$foldMap$1.apply(Free.scala:127)
	at cats.free.Free$$anonfun$foldMap$1.apply(Free.scala:124)
	at cats.package$$anon$1.tailRecM(package.scala:41)
	at cats.free.Free.foldMap(Free.scala:124)
	at com.gu.scanamo.Scanamo$.exec(Scanamo.scala:17)
```

**Comment by philwills** [comment]
Thanks for the detailed error report. I'll try and take a look.

**Comment by philwills** [comment]
Hi, I've tried to recreate this, but the test case I've made (https://github.com/guardian/scanamo/compare/155-test-case?expand=1) passes successfully.

Are you on the latest version of Scanamo?

**Comment by dtboctor** [comment]
I'm using v1.0.0-M1, is that the one that you are using as well?  The other thing is that I'm using this from within a Spark Streaming job, I'm not sure if something about it is losing necessary information.

**Comment by dtboctor** [comment]
I'll also qualify that we are using scala 2.11

**Comment by dtboctor** [comment]
OK, so I put more effort into this.  Number 1, I had to be explicit about the SymbolKeyCondition thing since there are multiple applicable implicit conversions since I'm using spark, I noticed your test didn't do that.  Would that be the source of the issue?  

Another thing, i built a jar from the head of the master branch and it appears to be working.  I had to change the code to 
``` 
Scanamo.exec(client)(
        table
          .filter(
            attributeExists('numTries)
              and attributeExists('numCorrect)
              and attributeExists('score)
              and attributeExists('responseTime)
              and ('gameId -> gameId)
              and symbolAttributeName('responseTime) > 0
              and symbolAttributeName('numTries) > 5

          )
          .limit(limit)
          .query('userId -> userId descending)
      )
```

Notice that I have to use `symbolAttributeName` now instead of `SymbolKeyCondition`, so something about this newer code works that didn't work with the older code.

**Comment by dtboctor** [comment]
Are you going to do another release soon with the latest code?  Any way we could speed it up?

**Comment by philwills** [comment]
Yes, hoping to put something out today.

**Comment by philwills** [comment]
1.0.0-M2 is now on Maven Central. Let me know if you're still seeing the issue.

**Comment by dtboctor** [comment]
Awesome, thanks so much, I'll try it out today and see if it's working.

**Comment by regiskuckaertz** [comment]
Assuming this one can be closed now.
