### ISSUE TITLE
Cant create ScanamoAlpakka with DynamoClient

### ISSUE THREAD

**Issue by k1s** [scanamo/scanamo#251]
Hi, I have an issue when trying to create a simple request 
`  val client = DynamoClient(DynamoSettings(system))
  ScanamoAlpakka.scan[String](client)(tableName)`

`An exception or error caused a run to abort: Found interface akka.stream.alpakka.dynamodb.scaladsl.DynamoClient, but class was expected 
java.lang.IncompatibleClassChangeError: Found interface akka.stream.alpakka.dynamodb.scaladsl.DynamoClient, but class was expected
	at com.gu.scanamo.ops.AlpakkaInterpreter$$anon$1.apply(AlpakkaInterpreter.scala:21)
	at com.gu.scanamo.ops.AlpakkaInterpreter$$anon$1.apply(AlpakkaInterpreter.scala:13)
	at cats.free.Free$$anonfun$foldMap$1.apply(Free.scala:155)
	at cats.free.Free$$anonfun$foldMap$1.apply(Free.scala:153)
	at cats.StackSafeMonad$class.tailRecM(StackSafeMonad.scala:15)
	at cats.instances.FutureInstances$$anon$1.tailRecM(future.scala:10)
	at cats.free.Free.foldMap(Free.scala:153)
	at cats.free.Free$$anonfun$foldMap$1.apply(Free.scala:156)
	at cats.free.Free$$anonfun$foldMap$1.apply(Free.scala:153)
	at cats.StackSafeMonad$class.tailRecM(StackSafeMonad.scala:15)
	at cats.instances.FutureInstances$$anon$1.tailRecM(future.scala:10)
	at cats.free.Free.foldMap(Free.scala:153)
	at com.gu.scanamo.ScanamoAlpakka$.exec(ScanamoAlpakka.scala:21)
	at com.gu.scanamo.ScanamoAlpakka$.scan(ScanamoAlpakka.scala:61)`

thanks

**Comment by Slakah** [comment]
Looks like this could be due to an alpakka version incompatability. Scanamo uses [`0.15.1`](https://github.com/scanamo/scanamo/blob/master/build.sbt#L177). It looks like `DynamoClient` has been changed from a `class` to a `trait` in the latest version https://github.com/akka/alpakka/pull/1057 .
