### ISSUE TITLE
Unable to marshall request to JSON in getAll batch operation

### ISSUE THREAD

**Issue by moh-sen** [scanamo/scanamo#260]
Hello,

executing getAll on an existing table with primary key named email (of type String) gives the following error: 

`com.amazonaws.SdkClientException: Unable to marshall request to JSON: Unable to marshall request to JSON: null
at com.amazonaws.services.dynamodbv2.model.transform.BatchWriteItemRequestProtocolMarshaller.marshall(BatchWriteItemRequestProtocolMarshaller.java:58)
at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeBatchWriteItem(AmazonDynamoDBClient.java:596)
at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.batchWriteItem(AmazonDynamoDBClient.java:581)
at com.gu.scanamo.ops.ScanamoInterpreters$$anon$1.apply(ScanamoInterpreters.scala:51)
at com.gu.scanamo.ops.ScanamoInterpreters$$anon$1.apply(ScanamoInterpreters.scala:30)
at cats.free.Free.$anonfun$foldMap$1(Free.scala:155)
at cats.package$$anon$1.tailRecM(package.scala:42)
at cats.free.Free.foldMap(Free.scala:153)
at cats.free.Free.$anonfun$foldMap$1(Free.scala:156)
at cats.package$$anon$1.tailRecM(package.scala:42)
at cats.free.Free.foldMap(Free.scala:153)
at com.gu.scanamo.Scanamo$.exec(Scanamo.scala:17)
`

Here is the code I try:

```
val client: AmazonDynamoDB = {
    val conf = new EndpointConfiguration(
      "apigateway.eu-central-1.amazonaws.com",
      "eu-central-1")
    AmazonDynamoDBClientBuilder.standard().withEndpointConfiguration(conf).build()
  }

case class Entry(email: String, name: String)

import com.gu.scanamo.syntax._
import com.gu.scanamo.{Scanamo, Table}

val emailTable = Table[Entry]("emails")

val ops = for {
  _   <- emailTable.putAll(Set(Entry("test1@example.com", "a"), Entry("test2@example.com", "b")))
  es <- emailTable.getAll(keys = 'email -> Set("test1@example.com", "test2@example.com"))
} yield es
    
val blackListedEntries = Scanamo.exec(client)(ops)
```

Am I missing something or is this just a bug?

Thank you!

**Comment by regiskuckaertz** [comment]
Hi @moh-sen Sorry for the late reply. It may be that `name` is a reserved word and `BatchWrite` does not support expression attribute names, so we can't properly encode it. If that's the case then sadly the only alternatives are (1) change the column name, (2) use `put` instead of `putAll`.
