### ISSUE TITLE
Error not caught: The number of conditions on the keys is invalid

### ISSUE THREAD

**Issue by dougdonohoe** [scanamo/scanamo#386]
I'm just learning scanamo and was trying to do a `get` with a composite key.  I eventually figured out the right way, but was stumped by the error handling.  Here is my code:

```
   case class Tagger(tagPrefix: String, tag: String, somethingElse: String)

    val client = LocalDynamoDB.client()

    LocalDynamoDB.createTable(client)("tags")('tagPrefix -> S, 'tag -> S)
    val table = Table[Tagger]("tags")
    logger.info(s"Table: $table")

    val put = Scanamo.exec(client)(table.put(Tagger("doug", "doug::zork", "something else")))
    logger.info(s"Put :$put")

    // this works
    var get = Scanamo.exec(client)(table.get('tagPrefix -> "doug" and 'tag -> "doug::zork"))
    logger.info(s"Get :$get")

    // this throws exception ... why isn't error returned in the Either?
    try {
      get = Scanamo.exec(client)(table.get('tag -> "doug::zork"))
      logger.info(s"Get :$get")
    } catch {
      case t: Throwable =>
        logger.error("Get failed", t)
    }
```

The 2nd `get`, in the try block throws an exception instead of returning it in an `Either`.  Why is this?

This is the exception:

```
com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: The number of conditions on the keys is invalid (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: b4134e73-47ea-4d07-9991-1be00abce598)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1695) ~[aws-java-sdk-core-1.11.483.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1350) ~[aws-java-sdk-core-1.11.483.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1101) ~[aws-java-sdk-core-1.11.483.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:758) ~[aws-java-sdk-core-1.11.483.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:732) ~[aws-java-sdk-core-1.11.483.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:714) ~[aws-java-sdk-core-1.11.483.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:674) ~[aws-java-sdk-core-1.11.483.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:656) ~[aws-java-sdk-core-1.11.483.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:520) ~[aws-java-sdk-core-1.11.483.jar:?]
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:4192) ~[aws-java-sdk-dynamodb-1.11.483.jar:?]
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:4159) ~[aws-java-sdk-dynamodb-1.11.483.jar:?]
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeGetItem(AmazonDynamoDBClient.java:2028) ~[aws-java-sdk-dynamodb-1.11.483.jar:?]
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.getItem(AmazonDynamoDBClient.java:1995) ~[aws-java-sdk-dynamodb-1.11.483.jar:?]
	at org.scanamo.ops.ScanamoInterpreters$$anon$1.apply(ScanamoInterpreters.scala:39) ~[scanamo_2.12-1.0.0-M9.jar:1.0.0-M9]
	at org.scanamo.ops.ScanamoInterpreters$$anon$1.apply(ScanamoInterpreters.scala:30) ~[scanamo_2.12-1.0.0-M9.jar:1.0.0-M9]
	at cats.free.Free.$anonfun$foldMap$1(Free.scala:155) ~[cats-free_2.12-1.3.1.jar:1.3.1]
	at cats.package$$anon$1.tailRecM(package.scala:42) ~[cats-core_2.12-1.3.1.jar:1.3.1]
	at cats.free.Free.foldMap(Free.scala:153) ~[cats-free_2.12-1.3.1.jar:1.3.1]
	at cats.free.Free.$anonfun$foldMap$1(Free.scala:156) ~[cats-free_2.12-1.3.1.jar:1.3.1]
	at cats.package$$anon$1.tailRecM(package.scala:42) ~[cats-core_2.12-1.3.1.jar:1.3.1]
	at cats.free.Free.foldMap(Free.scala:153) ~[cats-free_2.12-1.3.1.jar:1.3.1]
	at org.scanamo.Scanamo$.exec(Scanamo.scala:40) ~[scanamo_2.12-1.0.0-M9.jar:1.0.0-M9]
	at io.citrine.dynamo.ddb.ScanamoBug$.$anonfun$new$1(ScanamoBug.scala:36) ~[test-classes/:?]
	at io.citrine.dynamo.ddb.ScanamoBug$.$anonfun$new$1$adapted(ScanamoBug.scala:19) ~[test-classes/:?]
	at io.citrine.dynamo.ddb.DynamoFixture$.withDynamoLocal(DynamoFixture.scala:130) ~[test-classes/:?]
	at io.citrine.dynamo.ddb.ScanamoBug$.delayedEndpoint$io$citrine$dynamo$ddb$ScanamoBug$1(ScanamoBug.scala:19) ~[test-classes/:?]
	at io.citrine.dynamo.ddb.ScanamoBug$delayedInit$body.apply(ScanamoBug.scala:13) ~[test-classes/:?]
	at scala.Function0.apply$mcV$sp(Function0.scala:39) ~[scala-library-2.12.8.jar:?]
	at scala.Function0.apply$mcV$sp$(Function0.scala:39) ~[scala-library-2.12.8.jar:?]
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17) ~[scala-library-2.12.8.jar:?]
	at scala.App.$anonfun$main$1$adapted(App.scala:80) ~[scala-library-2.12.8.jar:?]
	at scala.collection.immutable.List.foreach(List.scala:392) [scala-library-2.12.8.jar:?]
	at scala.App.main(App.scala:80) [scala-library-2.12.8.jar:?]
	at scala.App.main$(App.scala:78) [scala-library-2.12.8.jar:?]
	at io.citrine.dynamo.ddb.ScanamoBug$.main(ScanamoBug.scala:13) [test-classes/:?]
	at io.citrine.dynamo.ddb.ScanamoBug.main(ScanamoBug.scala) [test-classes/:?]
```

I'm running against DynamoDbLocal.  This is the exception it generated:

```
16:07:21 [914108708-20] WARN  LocalDynamoDBServerHandler:376 - DynamoDBLocalServiceException exception occured
com.amazonaws.services.dynamodbv2.exceptions.DynamoDBLocalServiceException: The number of conditions on the keys is invalid
	at com.amazonaws.services.dynamodbv2.exceptions.AWSExceptionFactory.buildLocalServiceException(AWSExceptionFactory.java:93) ~[DynamoDBLocal-1.11.477.jar:?]
	at com.amazonaws.services.dynamodbv2.exceptions.AWSExceptionFactory.buildAWSException(AWSExceptionFactory.java:58) ~[DynamoDBLocal-1.11.477.jar:?]
[snip]
```

**Comment by regiskuckaertz** [comment]
This is because you are using the synchronous interpreter based on the `Id` type: at the end of the world, since it is essentially a function that produces an `A`, then it has no choice but to throw an exception. There are multiple solutions which we've been thinking about:

- add a synchronous interpreter using `Try` or `Either[Throwable, ?]`
- surface errors in the data channel, i.e. `A ~ Either[Throwable, B]`
- make our free algebra an instance of `MonadError`

We've been toying with both as they all have interesting uses, but the last one seems promising, as it will open up the possibility of error handling inside a scanamo computation (partial recovery, retry, etc.)
