### ISSUE TITLE
Upgrading from 1.0.0-M5 to M10 broke a custom DynamoFormat for Instant

### ISSUE THREAD

**Issue by alexwlchan** [scanamo/scanamo#424]
This is a cutdown version of some code we were using in 1.0.0-M5, with a custom formatter for Instant because Scanamo didn’t provide one:

```scala
import java.time.Instant

import com.gu.scanamo._
import com.gu.scanamo.error.DynamoReadError
import com.gu.scanamo.ops.ScanamoOps
import com.gu.scanamo.{DynamoFormat, Table}


case class Birthday(name: String, time: Instant)


object Main extends App {
  implicit val instantStringFormat = DynamoFormat.coercedXmap[Instant, String, IllegalArgumentException](
    Instant.parse(_)
  )(
    _.toString
  )

  val table = Table[Birthday]("birthdays")

  val birthday = Birthday(name = "Alex", time = Instant.now())

  val ops: ScanamoOps[Option[Either[DynamoReadError, Birthday]]] = table.put(birthday)
  println(ops)
}
```

This code would correctly store an Instant in DynamoDB as an ISO-8601 date string.

We upgraded to 1.0.0-M10 and tweaked the imports as follows:

```scala
import java.time.Instant

import org.scanamo.auto._
import org.scanamo.error.DynamoReadError
import org.scanamo.ops.ScanamoOps
import org.scanamo.{DynamoFormat, Table}


case class Birthday(name: String, time: Instant)


object Main extends App {
  implicit val instantStringFormat = DynamoFormat.coercedXmap[Instant, String, IllegalArgumentException](
    Instant.parse(_)
  )(
    _.toString
  )

  val table = Table[Birthday]("birthdays")

  val birthday = Birthday(name = "Alex", time = Instant.now())

  val ops: ScanamoOps[Option[Either[DynamoReadError, Birthday]]] = table.put(birthday)
  println(ops)
}
```

Running the same code now throws an error:

```
[error] (run-main-0) java.time.format.DateTimeParseException: Text '' could not be parsed at index 0
[error] java.time.format.DateTimeParseException: Text '' could not be parsed at index 0
[error] 	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
[error] 	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
[error] 	at java.time.Instant.parse(Instant.java:395)
[error] 	at Main$.$anonfun$instantStringFormat$1(Main.scala:14)
[error] 	at org.scanamo.DynamoFormat$.$anonfun$coerce$2(DynamoFormat.scala:203)
[error] 	at cats.syntax.EitherSyntax$CatchOnlyPartiallyApplied$.apply$extension(either.scala:31)
[error] 	at org.scanamo.DynamoFormat$.$anonfun$coerce$1(DynamoFormat.scala:203)
[error] 	at org.scanamo.DynamoFormat$$anon$3.$anonfun$default$1(DynamoFormat.scala:134)
[error] 	at scala.Option.flatMap(Option.scala:171)
[error] 	at org.scanamo.DynamoFormat$$anon$3.<init>(DynamoFormat.scala:134)
[error] 	at org.scanamo.DynamoFormat$.xmap(DynamoFormat.scala:131)
[error] 	at org.scanamo.DynamoFormat$.coercedXmap(DynamoFormat.scala:157)
[error] 	at Main$.delayedEndpoint$Main$1(Main.scala:15)
[error] 	at Main$delayedInit$body.apply(Main.scala:12)
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:34)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:76)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.App.main(App.scala:76)
[error] 	at scala.App.main$(App.scala:74)
[error] 	at Main$.main(Main.scala:12)
[error] 	at Main.main(Main.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.Run.invokeMain(Run.scala:93)
[error] 	at sbt.Run.run0(Run.scala:87)
[error] 	at sbt.Run.execute$1(Run.scala:65)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:77)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:252)
[error] 	at java.lang.Thread.run(Thread.java:745)
```

For some reason an empty string is being passed into our custom `DynamoFormat` mapper, and it throws an exception when we construct the Put operation.

It’s not clear why this is throwing, or indeed why the (string) ~> (Instant) formatter is being used in a Put operation – and although the new Instant formats in Scanamo itself are nice, that's no good for existing tables that are stored in the old format.

**Comment by regiskuckaertz** [comment]
ha, yeah the `default` value for `String` is the empty string in M10 because dynamo won't accept attribute values with the empty string. So when you use `coercedXmap`, the default value for `Instant` will be derived from the one for `String`, giving something like this:
```
@ Instant.parse("")
java.time.format.DateTimeParseException: Text '' could not be parsed at index 0
  java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
  java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
  java.time.Instant.parse(Instant.java:395)
  ammonite.$sess.cmd1$.$anonfun$res1$1(cmd1.sc:1)
  scala.Option.flatMap(Option.scala:188)
  ammonite.$sess.cmd1$.<init>(cmd1.sc:1)
  ammonite.$sess.cmd1$.<clinit>(cmd1.sc)
```
It occurs to me none of the utility methods we provide on `DynamoFormat` allow one to provide its own default value (if any).

Thank you for raising this, I'll fix asap.

**Comment by regiskuckaertz** [comment]
The fix will be released in the next milestone. Note that:
- if it may help, we provide java time formats in `scanamo-time` (don't hesitate to suggest more useful  ones)
- there is a mistake in your code, you should catch `DateTimeParseExceptionform`, not `IllegalArgumentException`

In any case, now `coercedXmap` and `xmap` have an additional parameter `Option[B] => Option[A]` that allows you to transform the default value for the underlying format if the read function fails. In this case, there is no sensible value for times so the solution is just to return nothing:
```scala
implicit val instantStringFormat = DynamoFormat.coercedXmap[Instant, String, DateTimeParseExceptionform](
  Instant.parse(_),
  _ => None
)(
  _.toString
)
```
